version: "3.8"

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      API_PORT: ${API_PORT}
      WEATHER_API_KEY: ${WEATHER_API_KEY}
      VITE_API_URL: ${VITE_API_URL}
    ports:
      - "${API_PORT}:${API_PORT}"
      - "5173:5173"
    depends_on:
      - postgres
    volumes:
      - ./api:/usr/src/app

volumes:
  pgdata:
